### ISSUE TITLE
Customizing `isPublic` bahaviour doesn't always take effect.

### ISSUE THREAD

**Issue by BahaaZidan** [n1ru4l/graphql-public-schema-filter#173]
I'm trying to reverse the bahaviour of the library. Instead of allow-listing, I want to implement deny-listing. I've read the README. I know it's not the ideal solution. But there's a restriction in our current setup that is forcing us to do deny-listing. At least for now.

So I started out by creating the type definitons for my new direction `@undocumented`:
```gql
directive @undocumented on OBJECT | FIELD_DEFINITION | ENUM | UNION | INTERFACE | INPUT_OBJECT | SCALAR | INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION
```

Then I customized the `isPublic` method to look for the existance of `@undocumented` instead of the default `@public` directive:
```ts
  return buildPublicSchema({
    schema: baseSchema,
    isPublic: (input: SharedExtensionAndDirectiveInformation): boolean => {
      const isPublic = !input.astNode?.directives
        ?.map((directive) => directive.name.value)
        .includes('undocumented');

      return isPublic;
    }
  });
```

And then I tried to annotate a type and a field defenition with `@undocumented`:
```gql
  type Lolo @undocumented {
    name: String
    dodo: Boolean
  }

  type Query {
    _empty: String @undocumented
  }
```

Expected behaviour: neither `Query._empty` nor  `Lolo` should be returned in the introspection schema.

Actual behaviour: Both fields are returned in the introspection schema.

If I remove my customization and use `@public`, the library is working as expected.

**Comment by n1ru4l** [comment]
This is because the isPublic check will `true` for the `ObjectType`, which in return makes all the fields on the type public, due to the nature of how the library is implemented.

https://github.com/n1ru4l/graphql-public-schema-filter/blob/5169495f25d0c9009a0ebf388c9066dd8ad55c62/src/public-schema-filter.ts#L108-L115

This library's intension was never to inverse the isPublic behavior. I am willing to accept contributions that make this possible without breaking the existing behavior. Maybe it might be possible by providing more arguments to `isPublic` e.g. the type name.

**Comment by BahaaZidan** [comment]
Thanks for the quick response. I'll close this issue for now.
